language: go
go: 1.3.3
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - export PATH=$PATH:${GOPATH%%:*}/bin:${GOPATH##:*}/bin

  - go get github.com/anonx/sunplate/... # Getting the dependencies for the repo.
  - go test -v github.com/anonx/sunplate/...
script:
  - cd ${GOPATH%%:*}/src/github.com/anonx/sunplate
  - COVERALLS="-service=travis-ci -repotoken $COVERALLS_TOKEN" sh ./coverage.sh
