language: go
go: 1.4
install:
  - export PATH=$PATH:${GOPATH%%:*}/bin:${GOPATH##:*}/bin

  - go get -t github.com/colegion/goal/skeleton/... # Getting the dependencies for the repo.
script:
  - go test -v github.com/colegion/goal/skeleton/...
